barbet: Switch to prebuilt camera
error: Unresolved symbol:
_ZN7android17google_camera_hal16ResultDispatcher6CreateEjNSt3__18functionIFvNS2_10unique_ptrINS0_13CaptureResultENS2_14default_deleteIS5_EEEEEEENS3_IFvRKNS0_13NotifyMessageEEEERKNS0_19StreamConfigurationENS2_17basic_string_viewIcNS2_11char_traitsIcEEEE

Change-Id: I41763ad224e87d33d1f4fcc2c41aae95a18507fd